### ISSUE TITLE
ios simple should compute the sum:

### ISSUE THREAD

**Issue by IceEnd** [appium/sample-code#100]
Hi , When I run
`npm run ios-simple`
There have a problem:

`1) ios simple should compute the sum:
     Error: [elementByIosUIAutomation(".elements().withName(\"Answer\");")] Error response status: 32, , InvalidSelector - Argument was an invalid selector (e.g. XPath/CSS). Selenium error: Locator Strategy '-ios uiautomation' is not supported for this session
      at exports.newError (node_modules/wd/lib/utils.js:139:13)
      at node_modules/wd/lib/callbacks.js:75:19
      at node_modules/wd/lib/webdriver.js:174:5
      at Request._callback (node_modules/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)`

What's This?

**Comment by imurchie** [comment]
Are you using Appium 1.6.0 with iOS 10? These need to be updated to handle the lack of UI Automation in that version.

**Comment by IceEnd** [comment]
Oh，yes，I using Appium 1.6.0 with iOS 10,thx!(PS: How long will it take to update the version？）
