### ISSUE TITLE
npm start won't start throwing syntax error

### ISSUE THREAD

**Issue by jhoyle61** [appium/sample-code#122]
> PodiumPartnerInstance@0.0.5 start C:\engage\podium.membersite
> nodemon --watch server server

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\engage\podium.membersite\server/**/*
[nodemon] starting `node server`
C:\engage\podium.membersite\env.js:1
(function (exports, require, module, __filename, __dirname) { pecific configuration
                                                                      ^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\engage\podium.membersite\webpack.config.js:1:73)
[nodemon] app crashed - waiting for file changes before starting...

not sure why this is happening, it's my first time using Node.js

**Comment by jlipps** [comment]
Hi, why are you running `nodemon` on this repo?

**Comment by jhoyle61** [comment]
i'm using to have my server restart when my code changes could this be an issue?

**Comment by jhoyle61** [comment]
i've sorted it out my env file wasn't copied over correctly 

Thank you for your help anyways
