### ISSUE TITLE
Ruby simple_test failed 

### ISSUE THREAD

**Issue by hahattan** [appium/sample-code#138]
New to this project, I just installed `npm`, `appium` and try to getting start by running `bundle exec rspec simple_test.rb`, but it gave the following error :
```
An error occurred while loading ./simple_test.rb.
Failure/Error: raise Selenium::WebDriver::Error::NoSuchElementError, error_message

Selenium::WebDriver::Error::NoSuchElementError:
  An element could not be located on the page using the given search parameters.
# /Users/HAHATTAN/.rvm/gems/ruby-2.4.2/gems/appium_lib-9.4.10/lib/appium_lib/common/helper.rb:219:in `_no_such_element'
# /Users/HAHATTAN/.rvm/gems/ruby-2.4.2/gems/appium_lib-9.4.10/lib/appium_lib/ios/helper.rb:216:in `ele_index'
# /Users/HAHATTAN/.rvm/gems/ruby-2.4.2/gems/appium_lib-9.4.10/lib/appium_lib/ios/element/button.rb:18:in `button'
# /Users/HAHATTAN/.rvm/gems/ruby-2.4.2/gems/appium_lib-9.4.10/lib/appium_lib/driver.rb:193:in `rescue in block (3 levels) in promote_singleton_appium_methods'
# /Users/HAHATTAN/.rvm/gems/ruby-2.4.2/gems/appium_lib-9.4.10/lib/appium_lib/driver.rb:190:in `block (3 levels) in promote_singleton_appium_methods'
# ./simple_test.rb:71:in `<module:IOS>'
# ./simple_test.rb:54:in `<module:Calculator>'
# ./simple_test.rb:53:in `<top (required)>'
# ------------------
# --- Caused by: ---
# NoMethodError:
#   super: no superclass method `button' for Calculator::IOS:Module
#   Did you mean?  buttons
#   /Users/HAHATTAN/.rvm/gems/ruby-2.4.2/gems/appium_lib-9.4.10/lib/appium_lib/driver.rb:191:in `block (3 levels) in promote_singleton_appium_methods'
No examples found.


Finished in 0.00068 seconds (files took 40.53 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

My appium version is `1.7.1` and ruby is `2.4.2`
I also changed the `platformVersion: '10.2',` in the source code to `11.0` or it'll complain about the only available SDK version is `11.0` on my system

Any idea how to fix this ?

**Comment by KazuCocoa** [comment]
Was the `TestApp.app` working during the test? @hahattan

**Comment by hahattan** [comment]
Not quite sure what's the right behavior of the `TestApp.app`, during the test it seemed `TestApp` is about to be executed (there's a segue showed `TestApp` is opened) but end up jumping back to the Home Menu

**Comment by KazuCocoa** [comment]
https://github.com/appium/sample-code/pull/139
I tried with 10.3 and then the app launched and the test passed. So, I think we re-build `TestApp` itself to be able to launch with iOS 11.

----

📝 We should update test app in this repository.
https://github.com/appium/sample-code/issues/135
https://github.com/appium/ios-test-app

**Comment by hahattan** [comment]
so I installed 10.3 and try to run `simple_test.rb` again but it still gave me the same error (which is about `button`). `TestApp` did open successfully this time though: ![](https://i.imgur.com/ygKyMv6.png)
It seemed I have to wait for the PR to get the updated `TestApp` ?

**Comment by KazuCocoa** [comment]
@hahattan I've merged the PR and could you check again?

**Comment by hahattan** [comment]
still got the same error after I updated repo

**Comment by KazuCocoa** [comment]
hm... I think `textfields` return a blank list `[]` as the result. So, not found error happened in `button(1).click`, I think. So, I guess we need to wait until finishing launch the test app.

```ruby
    # Find every textfield.
    elements     = textfields

    elements.each_with_index do |element, index|
      element.type values[index]
    end

    # Click the first button
    button(1).click
```

I probably think the test script can wait to finish launching the test app with the following diff.

```diff
+    wait { textfield } # Because `textfield` raise error  and nil if the element doesn't found

    # Find every textfield.
    elements     = textfields

    elements.each_with_index do |element, index|
      element.type values[index]
    end

    # Click the first button
    button(1).click
```
