### ISSUE TITLE
Error running Node.js samples 

### ISSUE THREAD

**Issue by PrasadSync** [appium/sample-code#146]
> mocha selendroid-simple.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'wd'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\prsn0001\SyncGit\sample-code-master\sample-c
ode-master\sample-code\examples\node\helpers\setup.js:1:72)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\prsn0001\SyncGit\sample-code-master\sample-c
ode-master\sample-code\examples\node\selendroid-simple.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Users\prsn0001\SyncGit\sample-code-master\sample-code-master\sample-co
de\examples\node\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\prsn0001\SyncGit\sample-code-master\sample-code
-master\sample-code\examples\node\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\Users\prsn0001\SyncGit\sample-code-master\sample-code-maste
r\sample-code\examples\node\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (C:\Users\prsn0001\SyncGit\sample-code-master\sample-c
ode-master\sample-code\examples\node\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-sample-code@1.0.0 selendroid-simple: `mocha selendroid-simple.js
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-sample-code@1.0.0 selendroid-simple script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\prsn0001\AppData\Roaming\npm-cache\_logs\2017-12-14T10_55_
44_306Z-debug.log

**Comment by trix0** [comment]
have you tried to write npm install in your project folder ?

**Comment by PrasadSync** [comment]
Yes

**Comment by imurchie** [comment]
We are in the process of fixing the sample code. In the meantime, you should be able to get beyond this particular error by manually installing `wd` (using `npm install wd`).
