### ISSUE TITLE
SyntaxError: Unexpected identifier on the first run

### ISSUE THREAD

**Issue by elliotchh** [appium/sample-code#73]
Hi,

I'm new to node.js, mocha and appium automation.
I got appium setup and running, but when I run "mocha android-simple.js", I got the error as below

  1) android simple "before all" hook:
     SyntaxError: Unexpected identifier
      at exports.runInThisContext (vm.js:53:16)
      at require (internal/module.js:12:17)
      at Context.<anonymous> (android-simple.js:21:15)

When I look at the line 21 of sample file, the line is 
      _.clone(require("./helpers/caps").android18) : 

I tried to find a solution but not working, anyone can help? Thanks a lot

**Comment by imurchie** [comment]
What version of node and npm are you using? 

Can you post the results from `npm ls`?

**Comment by elliotchh** [comment]
Thanks for reply, 
my node version is 4.3.0 and npm version is 3.6.0
and here is the result of npm ls

appium-sample-code@1.0.0 /Users/elliot/Downloads/sample-code-master/sample-code/examples/node
├─┬ chai@2.3.0
│ ├── assertion-error@1.0.0
│ └─┬ deep-eql@0.1.3
│   └── type-detect@0.1.1
├── chai-as-promised@5.2.0
├── colors@1.1.2
├─┬ express@4.13.4
│ ├─┬ accepts@1.2.13
│ │ ├─┬ mime-types@2.1.10
│ │ │ └── mime-db@1.22.0
│ │ └── negotiator@0.5.3
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── content-type@1.0.1
│ ├── cookie@0.1.5
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.1.0
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├─┬ finalhandler@0.4.1
│ │ └── unpipe@1.0.0
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.0.10
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.0.5
│ ├── qs@4.0.0
│ ├── range-parser@1.0.3
│ ├─┬ send@0.13.1
│ │ ├── destroy@1.0.4
│ │ ├─┬ http-errors@1.3.1
│ │ │ └── inherits@2.0.1
│ │ ├── mime@1.3.4
│ │ └── statuses@1.2.1
│ ├── serve-static@1.10.2
│ ├─┬ type-is@1.6.11
│ │ └── media-typer@0.3.0
│ ├── utils-merge@1.0.0
│ └── vary@1.0.1
├─┬ q@2.0.3
│ ├── asap@2.0.3
│ ├── pop-iterate@1.0.1
│ └── weak-map@1.0.5
├── underscore@1.8.3
└─┬ wd@0.3.12
  ├─┬ archiver@0.14.4
  │ ├── async@0.9.2
  │ ├── buffer-crc32@0.2.5
  │ ├─┬ glob@4.3.5
  │ │ ├─┬ inflight@1.0.4
  │ │ │ └── wrappy@1.0.1
  │ │ ├─┬ minimatch@2.0.10
  │ │ │ └─┬ brace-expansion@1.1.3
  │ │ │   ├── balanced-match@0.3.0
  │ │ │   └── concat-map@0.0.1
  │ │ └── once@1.3.3
  │ ├── lazystream@0.1.0
  │ ├── lodash@3.2.0
  │ ├─┬ readable-stream@1.0.33
  │ │ ├── core-util-is@1.0.2
  │ │ ├── isarray@0.0.1
  │ │ └── string_decoder@0.10.31
  │ ├─┬ tar-stream@1.1.5
  │ │ ├── end-of-stream@1.1.0
  │ │ └── xtend@4.0.1
  │ └─┬ zip-stream@0.5.2
  │   ├─┬ compress-commons@0.2.9
  │   │ ├── crc32-stream@0.3.4
  │   │ └── node-int64@0.3.3
  │   └── lodash@3.2.0
  ├── async@1.0.0
  ├── lodash@3.9.3
  ├── q@1.4.1
  ├─┬ request@2.55.0
  │ ├── aws-sign2@0.5.0
  │ ├── bl@0.9.5
  │ ├── caseless@0.9.0
  │ ├─┬ combined-stream@0.0.7
  │ │ └── delayed-stream@0.0.5
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@0.2.0
  │ │ ├── async@0.9.2
  │ │ └─┬ mime-types@2.0.14
  │ │   └── mime-db@1.12.0
  │ ├─┬ har-validator@1.8.0
  │ │ ├── bluebird@2.10.2
  │ │ ├─┬ chalk@1.1.1
  │ │ │ ├── ansi-styles@2.1.0
  │ │ │ ├── escape-string-regexp@1.0.4
  │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ ├── strip-ansi@3.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ └─┬ is-my-json-valid@2.13.0
  │ │   ├── generate-function@2.0.0
  │ │   ├─┬ generate-object-property@1.2.0
  │ │   │ └── is-property@1.0.2
  │ │   └── jsonpointer@2.0.0
  │ ├─┬ hawk@2.3.1
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@0.10.1
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.5
  │ │ └── ctype@0.5.3
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.0.14
  │ │ └── mime-db@1.12.0
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.6.0
  │ ├── qs@2.4.2
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.1
  │ └── tunnel-agent@0.4.2
  ├── underscore.string@3.0.3
  └── vargs@0.1.0

**Comment by imurchie** [comment]
Can you delete your dependencies (`rm -rf node_modules`) and then re-install (`npm install`)? The tests run on my machine with your configuration:


```
isaac node → git master → node --version
v4.3.0
isaac node → git master → npm --version
3.6.0
isaac node → git master → mocha android-simple.js

  android simple
 > CALL init({"browserName":"","appium-version":"1.3","platformName":"Android","platformVersion":"4.4.2","deviceName":"Android Emulator","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"})
 > POST /session {"desiredCapabilities":{"browserName":"","appium-version":"1.3","platformName":"Android","platformVersion":"4.4.2","deviceName":"Android Emulator","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"}}

Driving the web on session: 0cf5c83b-190f-4ab4-80b5-ab6f95dc44ed

 > RESPONSE init({"browserName":"","appium-version":"1.3","platformName":"Android","platformVersion":"4.4.2","deviceName":"Android Emulator","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"}) "0cf5c83b-190f-4ab4-80b5-ab6f95dc44ed",{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"","appium-version":"1.3","platformName":"Android","platformVersion":"4.4.2","deviceName":"Android Emulator","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"},"browserName":"","appium-version":"1.3","platformName":"Android","platformVersion":"4.4.4","deviceName":"emulator-5554","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"}
 > CALL setImplicitWaitTimeout(3000)
 > POST /session/:sessionID/timeouts/implicit_wait {"ms":3000}
 > RESPONSE setImplicitWaitTimeout(3000)
 > CALL elementByAccessibilityId("Graphics")
 > POST /session/:sessionID/element {"using":"accessibility id","value":"Graphics"}
    ✓ should find an element (123ms)
 > CALL quit()
 > DELETE /session/:sessionID

Ending your web drivage..

 > RESPONSE quit()

  1 passing (1m)
```

**Comment by elliotchh** [comment]
I tried remove the node_modules directory and re-install it with "npm install", but the error still appear. how ever, I have another directory stored some of my test script, and I copy the node_modules to sample-code/examples/node/. There has no error come out, but the mocha test return success before the app start at my emulator... T_T

When I compare the list or module between two node_modules directories, the package list is the same (version number also).

**Comment by imurchie** [comment]
Very strange. I don't know what to do going forward.
